### ISSUE TITLE
Effection Website

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/effection#334]
## Motivation
We need API docs and guides for Effection. Jorge initialized the website in #276 and listed out some use cases, but we still have a long way to go and this issue will try to outline what needs to be done and who should be doing what.

### Navigation Bar
![Screen Shot 2021-05-26 at 8 38 55 AM](https://user-images.githubusercontent.com/29791650/119661211-106f3b00-bdfe-11eb-85d0-6e0bd1c9dc6a.png)
At the moment, I think we just need these top-level pages:
- `/` - We can display features here similar to the [landing page](https://frontside.com/bigtest/interactors) of our `Interactors` website
- `/Guides`- This section will include all of the use-case examples (which we'll be referring to as the Cookbook) and explain the fundamental concepts.
- `/API-Docs` - Auto-generated API docs
- ❓ `/About` - This About page is included in #276 and we also have an About page on the bigtest website but I'm not sure if it'll be necessary. We'll be discussing a lot of the core concepts and the context around why effection came to be in the `Guides` section. But maybe we'll find the need to move some of that content over to the About page? We'll see.

### Guides
The guides is divided into five sections:

#### 1. `Introduction` - _What is Effection_
- What kind of problems can Effection solve? (Big picture stuff and sample examples)
- Overview of the guides:
    `Effection is yada yada, go to Why Effection for a deeper understanding of the core concepts, the Guide to Effection Packages will summarize and explain what each package is for and when to use them, and the cookbook has examples of common use case scenarios.`

#### 2. `Why Effection` - _Why should I use Effection_
- This section will describe the fundamentals/features of Effection (including structured concurrency) by describing the common problem and explaining how Effection solves that issue:
  - "No memory leaks"
  - "No runaway processes"
  - "No uncaught errors"
    - @cowboyd i know we discussed having a separate page for "How Effection solves these problems" but can't we just include each individual solution for each problem? Or does it make more sense to list out all the problems first and tackle them all at once?
      | option A | option B | 
      | --- | --- |
      | Introduction <br> Issue <br> Issue <br> Issue <br> Solution | Introduction <br> Issue + Solution <br> Issue + Solution <br> Issue + Solution |

#### 3. `Guide to Effection Packages` - _Which Effection package am I supposed to use?_
- This section will describe what each package is for and describe a scenario where they would need it.
  - For a new user approaching Effection, they might be wondering "what? there are so many packages? what's atom? and what's fetch? if i install `@effection/jest`, do i still need to install `effection`?"
  
#### 4. `Effection Cookbook` - _How can I use Effection?_
- Overview: List all the examples and summarize what it can achieve
  - Maybe we can have an `@effection/sample-app` with all the examples?
- Recipes:
  - Running multiple processes
  - Subscribing to stuff
  - Catching errors to external processes
  - Well behaved CLI 
  - Closing Sockets
  - File watcher
  - Interprocess communication
  - Type Ahead
  - ...
  
The recipes list is incomplete and depending on how many we end up with, we'll need to restructure the menu here. Perhaps we can categorize the examples.

#### 5. `Debugging with Effection`
So this _could_ go in the cookbook but it's not so much an example but an Effection feature guide so I think it's appropriate for it to have its own section. 🤷‍♂️

## TODOs
- [ ] Create `@effection/jest`
- [ ] Finish debugger
- [x] Which tool should we use to auto-generate API docs?
- [ ] Brainstorm for missing recipes
- [ ] Write out the examples for the existing recipes

**Comment by cowboyd** [comment]
We have a website for Effection now right? I'm going to close this, and we can open up future issues to track work that will happen.
