### ISSUE TITLE
Finishing the migration to covector from changesets

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/effection#433]
Part II of #420

In order to complete the switch over to covector, we need to finish removing changesets in an orderly fashion:

## Current PRs
If they already created new changeset files in a PR, they should ~~either~~... 
1. Delete the changesets files, rebase their branch, and generate covector's change files.
    - Merging PRs with covectors' change files will generate a separate covector's version-packages PR.
    
~~2. Merge the PR normally.~~
    ~~- The changesets workflow is still available on this monorepo (and will be operational again once we merge #432) so if anyone merges their PR with changesets, it will be added and squashed on the changeset-generated version-packages PR #431.~~
      ~~- Merging the changesets' version-packages PR will utilize covector's publishing mechanism (the original release workflow was replaced with covector's version-or-publish workflow; both of these actions work by checking if a package at its current version exists on the registry before attempting to publish).~~
      
☝️ This doesn't work very well because having covector files in the main branch will prevent the changeset bumps from publishing. So I've gone ahead and deleted the changeset workflow, went down the list of all the open PRs and removed all changeset files and converted new changeset files to covector change files:

  - #439
  - #440

## New PRs
New branches won't have changesets in the monorepo dependency so they won't be able to generate new changesets via CLI. Hopefully no one will manually create changesets files. 🤞

## TODOs
- [x] ~~Wait for all current PRs to either merge or be rebased~~
  - [x] ⚠️ ~~Before merging either covector or changesets version-packages PR, someone might need to pull the branch and manually rebase with the main branch. This is because changesets and covector might only rebase when a new change/changeset file is merged to the main branch. If one version-packages pr is merged and then the second version-packages pr is merged right afterwards, the second version-packages pr might not have a chance to rebase and correctly re-apply the changes with the new versions. However, if the first version-packages pr is merged and then a new covector change file is merged to the main branch, the second version-packages pr will for sure rebase successfully on its own. So to be safe, we'll double check the version-packages pr before merging.~~
    - [x] ~~Once changesets' version-packages PR is merged and we can confirm that all current PRs have rebased (so that no more changeset files will be generated), we can remove the app and workflow.~~
    
⚠️ I overlooked the scenario where we have covector files while trying to publish bumps from changeset. Although we could've waited until we merged a covector's `version packages` pr to publish both covector and changeset bumps, I wasn't sure what kind of other bugs might be introduced so I've gone through the process of converting all changeset files to covector change files and preemptively removed the changeset workflow.
- [x] After #440 is merged, I will add the pre-existing covector file back in its rightful place (had to put it elsewhere to allow publishing of the changeset bumps).
  - #448 
- [x] Remove changeset bot access to this monorepo.
